ci/cd 15

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,17 +17,21 @@ jobs:
         run: mvn install -DskipTests=true
 
       - name: Deploy JAR
-        env:
-          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
-          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
-          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
-          JWT_SECRET: ${{ secrets.JWT_SECRET }}
-          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
-          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
-          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
         run: |
+          export SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
+          export SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
+          export SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
+          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
+          export SPRING_MAIL_USERNAME="${{ secrets.SPRING_MAIL_USERNAME }}"
+          export SPRING_MAIL_PASSWORD="${{ secrets.SPRING_MAIL_PASSWORD }}"
+          export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
+
           pkill -f 'demo-0.0.1-SNAPSHOT.jar' || true
           rm -rf /projects/SocialNetwork/SocialNetworkBE/*
           cp -r target/* /projects/SocialNetwork/SocialNetworkBE/
-          cd /projects/SocialNetwork/SocialNetworkBE/
-          nohup java -jar /projects/SocialNetwork/SocialNetworkBE/demo-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
+
+          cd /projects/SocialNetwork/SocialNetworkBE
+          nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+          sleep 10
+          cat app.log || echo "App log not found"
+          ps aux | grep demo || echo "Process not found"
